// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static AnalogChannel* driveTrainFrontLeftPos;
	static SpeedController* driveTrainFrontLeftSteer;
	static PIDController* driveTrainFrontLeft;
	static AnalogChannel* driveTrainFrontRightPos;
	static SpeedController* driveTrainFrontRightSteer;
	static PIDController* driveTrainFrontRight;
	static AnalogChannel* driveTrainRearLeftPos;
	static SpeedController* driveTrainRearLeftSteer;
	static PIDController* driveTrainRearLeft;
	static AnalogChannel* driveTrainRearRightPos;
	static SpeedController* driveTrainRearRightSteer;
	static PIDController* driveTrainRearRight;
	static Gyro* driveTrainGyro;
	static SpeedController* driveTrainFrontLeftDrive;
	static SpeedController* driveTrainFrontRightDrive;
	static SpeedController* driveTrainRearLeftDrive;
	static SpeedController* driveTrainRearRightDrive;
	static Compressor* shooterComp;
	static Solenoid* shooterFireLeft;
	static Solenoid* shooterFireRight;
	static Solenoid* shooterLeftArm;
	static Solenoid* shooterRightArm;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
